version: "1.0"
services:
  redis:
    image: redis
    volumes:
      - ./store:/var/log
  counter:
    build: ./counter
    environment:
      - PORT=3000
      - REDIS_URL=redis
  library:
    build: .
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_URL=counter:3000
    links:
      - counter
